language: java
jdk:
  - oraclejdk8
#  - openjdk8

after_success:
  - mvn clean test jacoco:report coveralls:report

notifications:
  email:
    recipients:
      - gr-tig-oss@future.co.jp
    on_success: never # default: change
    on_failure: always # default: always
